$(document).ready(function(){
  $(".allKinds").click(function(){
    $("#all").fadeToggle();
    $(".all-list").slideToggle();
    $(".smart-order-list").hide();
    $(".city-list").hide();
    $('div[class*="sub"]').hide();
    $("#all-city").hide();
    $("#smart-order").hide();
    $("body").css("position","fixed");

  });
 
  $(".allCity").click(function(){
    $(".all-list").hide();
    $(".smart-order-list").hide();
    $('div[class*="sub"]').hide();
    $('#all-city').fadeToggle();
    $("#all").hide();
    $("#smart-order").hide();
    $(".city-list").slideToggle();
    $("body").css("position","fixed");
   
  });

  $(".smartOrder").click(function(){
    $(".all-list").hide();
    $(".city-list").hide();
    $("#all").hide();
    $("#all-city").hide();
    $('div[class*="sub"]').hide();
    $(".smart-order-list").slideToggle();
    $("#smart-order").fadeToggle();
    $("body").css("position","fixed");
  });

  //点击遮罩消失
  $("#all").click(function(){
    $(this).hide();
    $(".all-list").hide();
    $('div[class*="sub"]').hide();
    $("body").css("position","relative");
  });
  $("#all-city").click(function(){
    $(this).hide();
    $(".city-list").hide();
    $('div[class*="sub"]').hide();
    $("body").css("position","relative");
  });
  $("#smart-order").click(function(){
    $(this).hide();
    $(".smart-order-list").hide();
    $('div[class*="sub"]').hide();
    $("body").css("position","relative");
  });
  // 一级菜单
  $(".meishi").click(function(){
    $(this).css("color","#E60827");
    $(this).siblings().css("color","#333");
    $('div[class$="item"]').hide();
    $(".meishi-list-item").show(); 
  });
  $(".shopping").click(function(){
    $(this).css("color","#E60827");
    $(this).siblings().css("color","#333");
    $('div[class$="item"]').hide();
    $(".shopping-list").show();
  });
  $(".fun").click(function(){
    $(this).css("color","#E60827");
    $(this).siblings().css("color","#333");
    $('div[class$="item"]').hide();
    $(".fun-list").show();
  });
  $(".live").click(function(){
    $(this).css("color","#E60827");
    $(this).siblings().css("color","#333");
    $('div[class$="item"]').hide();
    $(".live-list").show();
  });
  $(".education").click(function(){
    $(this).css("color","#E60827");
    $(this).siblings().css("color","#333");
    $('div[class$="item"]').hide();
    $(".education-list").show();
  });
  $(".hotel").click(function(){
    $(this).css("color","#E60827");
    $(this).siblings().css("color","#333");
    $('div[class$="item"]').hide();
    $(".hotel-list").show();
  });
  $(".trip").click(function(){
    $(this).css("color","#E60827");
    $(this).siblings().css("color","#333");
    $('div[class$="item"]').hide();
    $(".trip-list").show();
  });
});